<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="JoonHo Lee (jlee296@ua.edu)">
<meta name="author" content="Mehdi Rajeb">
<meta name="dcterms.date" content="2022-11-27">

<title>Chapter 3. Random-intercept models with covariates</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="03_Random_Intercept_models_files/libs/clipboard/clipboard.min.js"></script>
<script src="03_Random_Intercept_models_files/libs/quarto-html/quarto.js"></script>
<script src="03_Random_Intercept_models_files/libs/quarto-html/popper.min.js"></script>
<script src="03_Random_Intercept_models_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="03_Random_Intercept_models_files/libs/quarto-html/anchor.min.js"></script>
<link href="03_Random_Intercept_models_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="03_Random_Intercept_models_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="03_Random_Intercept_models_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="03_Random_Intercept_models_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="03_Random_Intercept_models_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Chapter 3. Random-intercept models with covariates</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>JoonHo Lee (jlee296@ua.edu) </p>
             <p>Mehdi Rajeb </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 27, 2022</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction-3.1" class="level1">
<h1>Introduction (3.1)</h1>
<p>In this chapter, the variance-component model is extended to introduce random-intercept models with covariates.Readers can easily identify several overlapping features of variance-component models with random-intercept model, however, this chapter will introduce the differences between within-cluster and between-cluster covariate effects.</p>
<section id="does-smoking-during-pregancy-affect-birthweight-3.2" class="level2">
<h2 class="anchored" data-anchor-id="does-smoking-during-pregancy-affect-birthweight-3.2">Does smoking during pregancy affect birthweight? (3.2)</h2>
<p>The data used in this chapter investigates the effect of smoking on birth outcomes with the Natality data sets derived from birth certificates by the U.S. National Center for Health Statistics. The dataset used by <span class="citation" data-cites="abrevaya2006estimating">@abrevaya2006estimating</span> is available from the Journal of Apllied Econometrics Data Archive. The data set contains 8604 births from 3978 mothers. Also following variables are available in the data set <code>smoking.dta</code>.</p>
<ul>
<li><p><code>momid</code>: mother identifier</p></li>
<li><p><code>birwt</code>: birth weight (in grams)</p></li>
<li><p><code>smoke</code>: dummy variable for mother smoking during pregnancy (1: smoking; 0: not smoking)</p></li>
<li><p><code>male</code>: dummy variable for baby being male (1: male , 0: female)</p></li>
<li><p><code>meduc</code>: mother’s education (reference category: did not graduate from high school)</p>
<ul>
<li><p><code>hsgrad</code>: dummy variable for having graduated from high school ( 1: graduated; 0: otherwise)</p></li>
<li><p><code>somecoll</code>: dummy variable for having some college education, but no degree (1: some college; 0: otherwise)</p></li>
<li><p><code>collgrad</code>: dummy variable for having graduated from college (1: graduated; 0: otherwise)</p></li>
</ul></li>
<li><p><code>married</code>: dummy variable for mother being married (1: married; 0: unmarried)</p></li>
<li><p><code>black</code> : dummy variable for mother being Black(1: Black; 0: White)</p></li>
<li><p>Kessner index (reference category: Kessner index = 1, or adequate prenatal care)</p>
<ul>
<li><p><code>kessner2</code>: dummy variable for Kessner index = 2, or intermediate prenatal care (1: index = 2; 0: otherwise)</p></li>
<li><p><code>kessner3</code>: dummy variable for Kessner index = 3, or inadequate prenatal care (1: index=3; 0: otherwise)</p></li>
</ul></li>
<li><p>Timing of first prenatal visit(reference category: first trimester)</p>
<ul>
<li><p><code>novisit</code>: dummy variable for no prenatal care visit(1: no visit; 0: otherwise)</p></li>
<li><p><code>pretri2</code>: dummy variable for first prenatal care visit having occurred in second trimester( 1: yes; 0: otherwise)</p></li>
<li><p><code>pretri3</code>: dummy variable for first prenatal care visit having occurred in third trimester (1: yes; 0: otherwise)</p></li>
</ul></li>
</ul>
</section>
<section id="data-structure-and-descriptive-statistics3.2.1" class="level2">
<h2 class="anchored" data-anchor-id="data-structure-and-descriptive-statistics3.2.1">Data structure and descriptive statistics(3.2.1)</h2>
<p>The data has two-level structure with births (or children or pregnancies) as unit level 1 and mothers as cluster at level 2. It is important to understand that in multilevel models, the dependent / response variable varies at the lowest level for different values of different level 1 units within the same level of cluster. It is also important to understand whether variables vary at levels 1 and levels 2 but also to understand how much they vary at each of the levels.</p>
<p>let us have a look at the <code>smoking.dta</code> data set.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us get the data loaded in R</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"smoking.dta"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># let us have a look at the data.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 24
  momid   idx stateres   mage meduc mplbir    nlbnl gestat birwt  cigs smoke    
  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl+lbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl+lbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl+lbl&gt;
1    14     1 1 [AL]       16    10 47 [VA]       0     24  2790     0 0 [Nonsm…
2    14     2 1 [AL]       17    10 47 [VA]       1     42  2693     0 0 [Nonsm…
3    14     3 1 [AL]       20    10 47 [VA]       2     39  3600     0 0 [Nonsm…
4    25     1 1 [AL]       23    11 31 [NJ]       2     41  2778     0 0 [Nonsm…
5    25     2 1 [AL]       24    11 31 [NJ]       3     37  2835     0 0 [Nonsm…
6    25     3 1 [AL]       26    11 31 [NJ]       4     40  3402     0 0 [Nonsm…
# … with 13 more variables: male &lt;dbl+lbl&gt;, year &lt;dbl&gt;, married &lt;dbl&gt;,
#   hsgrad &lt;dbl&gt;, somecoll &lt;dbl&gt;, collgrad &lt;dbl&gt;, magesq &lt;dbl&gt;,
#   black &lt;dbl+lbl&gt;, kessner2 &lt;dbl&gt;, kessner3 &lt;dbl&gt;, novisit &lt;dbl&gt;,
#   pretri2 &lt;dbl&gt;, pretri3 &lt;dbl&gt;</code></pre>
</div>
</div>
<p>It is useful to know not just whether variables vary at levels 1 and 2 but also how much they vary at each of the levels. To do so, we write the following R-function for specific variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># R code for xtsum function</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us select the variables of interests.</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>df_temp <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(momid, idx, birwt, smoke, black)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># my_xtsum function: equivalent to Stata's xtsum command. </span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>my_xtsum <span class="ot">&lt;-</span> <span class="cf">function</span>(data, group_id, y){</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Define a function to calculate summary statistics</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  sum_stat <span class="ot">&lt;-</span> <span class="cf">function</span>(data, y ){</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    data <span class="sc">%&gt;%</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>      <span class="fu">summarize</span>(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>        <span class="at">Mean =</span> <span class="fu">mean</span>({{y}}, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>        <span class="at">Std.dev. =</span> <span class="fu">sd</span>({{y}}, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>        <span class="at">Min =</span> <span class="fu">min</span>({{y}}, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>        <span class="at">Max =</span> <span class="fu">max</span>({{y}}, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">N =</span> <span class="fu">n</span>()</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>      )</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  }</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Overall </span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>  vec_overall <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum_stat</span>({{y}})</span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Between</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>  vec_between <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>({{group_id}}) <span class="sc">%&gt;%</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>      <span class="at">gr_mean =</span> <span class="fu">mean</span>({{y}}, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    <span class="fu">sum_stat</span>(<span class="at">y =</span> gr_mean)</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Within</span></span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>  vec_within <span class="ot">&lt;-</span> data <span class="sc">%&gt;%</span></span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>({{group_id}}) <span class="sc">%&gt;%</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>    <span class="fu">mutate</span>(</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a>      <span class="at">gr_mean =</span> <span class="fu">mean</span>({{y}}, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a>      <span class="at">dev =</span> {{y}} <span class="sc">-</span> gr_mean, </span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>      <span class="at">size =</span> <span class="fu">n</span>()</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span></span>
<span id="cb3-41"><a href="#cb3-41" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span></span>
<span id="cb3-42"><a href="#cb3-42" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(</span>
<span id="cb3-43"><a href="#cb3-43" aria-hidden="true" tabindex="-1"></a>      <span class="at">Mean =</span> <span class="fu">mean</span>(dev, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> vec_overall<span class="sc">$</span>Mean, </span>
<span id="cb3-44"><a href="#cb3-44" aria-hidden="true" tabindex="-1"></a>      <span class="at">Std.dev. =</span> <span class="fu">sd</span>(dev, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), </span>
<span id="cb3-45"><a href="#cb3-45" aria-hidden="true" tabindex="-1"></a>      <span class="at">Min =</span> <span class="fu">min</span>(dev, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> vec_overall<span class="sc">$</span>Mean, </span>
<span id="cb3-46"><a href="#cb3-46" aria-hidden="true" tabindex="-1"></a>      <span class="at">Max =</span> <span class="fu">max</span>(dev, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> vec_overall<span class="sc">$</span>Mean, </span>
<span id="cb3-47"><a href="#cb3-47" aria-hidden="true" tabindex="-1"></a>      <span class="at">N =</span> <span class="fu">mean</span>(size)</span>
<span id="cb3-48"><a href="#cb3-48" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-49"><a href="#cb3-49" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb3-50"><a href="#cb3-50" aria-hidden="true" tabindex="-1"></a>  xtsum<span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(</span>
<span id="cb3-51"><a href="#cb3-51" aria-hidden="true" tabindex="-1"></a>    vec_overall, </span>
<span id="cb3-52"><a href="#cb3-52" aria-hidden="true" tabindex="-1"></a>    vec_between, </span>
<span id="cb3-53"><a href="#cb3-53" aria-hidden="true" tabindex="-1"></a>    vec_within</span>
<span id="cb3-54"><a href="#cb3-54" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb3-55"><a href="#cb3-55" aria-hidden="true" tabindex="-1"></a>  xtsum<span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(xtsum)</span>
<span id="cb3-56"><a href="#cb3-56" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rownames</span>(xtsum)<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"overall"</span>, <span class="st">"between"</span>, <span class="st">"within"</span>) </span>
<span id="cb3-57"><a href="#cb3-57" aria-hidden="true" tabindex="-1"></a>  xtsum</span>
<span id="cb3-58"><a href="#cb3-58" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We specified the <code>my_xtsum()</code> function. Let us calculate the between group and within group summary statistics.</p>
<ul>
<li>Summary statistics for <code>birwt</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics of birwt</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">my_xtsum</span>(df_temp, momid, birwt)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            Mean Std.dev.      Min      Max           N
overall 3469.931 527.1394  284.000 5642.000 8604.000000
between 3467.225 451.1943 1361.000 5183.500 3978.000000
within  3469.931 276.7966 1528.431 5411.431    2.225941</code></pre>
</div>
</div>
<ul>
<li>Summary statistics for <code>smoke</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics of Smoke</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">my_xtsum</span>(df_temp, momid, smoke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>             Mean  Std.dev.        Min       Max           N
overall 0.1399349 0.3469397  0.0000000 1.0000000 8604.000000
between 0.1424501 0.3216459  0.0000000 1.0000000 3978.000000
within  0.1399349 0.1368006 -0.5267318 0.8066016    2.225941</code></pre>
</div>
</div>
<ul>
<li>Summary statistics for <code>black</code></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summary statistics of black</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="fu">my_xtsum</span>(df_temp, momid, black)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Mean  Std.dev.        Min        Max           N
overall 0.07171083 0.2580235 0.00000000 1.00000000 8604.000000
between 0.07139266 0.2575120 0.00000000 1.00000000 3978.000000
within  0.07171083 0.0000000 0.07171083 0.07171083    2.225941</code></pre>
</div>
</div>
<p>In this case, the total number of observations is N =8604 and the number of clusters is 3978.</p>
<p>Lets consider the mean across mothers, or the proportion of mothers who are <code>black</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Summarizeing data for only unique mothers who are black. </span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>df_black<span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(momid) <span class="sc">%&gt;%</span> </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mean_black =</span> <span class="fu">mean</span>(black, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(momid, <span class="at">.keep_all =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>( </span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>             <span class="at">Obs =</span> <span class="fu">n</span>(), </span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>             <span class="at">Mean =</span> <span class="fu">mean</span>(mean_black, <span class="at">na.rm =</span> T), </span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">Std.Dev. =</span> <span class="fu">sd</span>(mean_black, <span class="at">na.rm=</span> T), </span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>             <span class="at">Min =</span> <span class="fu">min</span>(mean_black, <span class="at">na.rm=</span>T), </span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>             <span class="at">Max =</span> <span class="fu">max</span>(mean_black, <span class="at">na.rm=</span>T)</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>             )</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>df_black <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(df_black)</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(df_black)<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'black'</span>)</span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>df_black</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       Obs       Mean Std.Dev. Min Max
black 3978 0.07139266 0.257512   0   1</code></pre>
</div>
</div>
<p>We can also calculate the number of children per mother.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Counting number of child per mother</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df_child <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(momid) <span class="sc">%&gt;%</span> </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(momid) <span class="sc">%&gt;%</span> </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Nc =</span> <span class="fu">n</span>())<span class="sc">%&gt;%</span> </span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(momid, <span class="at">.keep_all =</span> T) </span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Frequency distribution for children per mother.</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>epiDisplay<span class="sc">::</span><span class="fu">tab1</span>(df_child<span class="sc">$</span>Nc,  <span class="at">cum.percent =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="03_Random_Intercept_models_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>df_child$Nc : 
        Frequency Percent Cum. percent
2            3330    83.7         83.7
3             648    16.3        100.0
  Total      3978   100.0        100.0</code></pre>
</div>
</div>
<p>For level-1 variables such as smoke, we can also produce tables of overall summaries.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Overall percentage of smokers</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>epiDisplay<span class="sc">::</span><span class="fu">tab1</span>(df<span class="sc">$</span>smoke, <span class="at">cum.percent =</span> F)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="03_Random_Intercept_models_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>df$smoke : 
        Frequency Percent
0            7400      86
1            1204      14
  Total      8604     100</code></pre>
</div>
</div>
<p>We can also calculate <code>between-group</code> percentages.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Between group percentages.</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Group percentages for smokers</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>btwn_s<span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(momid, smoke) <span class="sc">%&gt;%</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n_distinct</span>(momid),</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">momid=</span> momid, </span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoke =</span> smoke</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(smoke <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(momid) <span class="sc">%&gt;%</span></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(momid, <span class="at">.keep_all =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">summarise</span>(</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">Freq =</span> <span class="fu">n</span>(), </span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    <span class="at">Percent =</span> Freq<span class="sc">/</span>N[<span class="dv">1</span>]</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>  <span class="co">#Group percentages for non-smokers</span></span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>btwn_ns<span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(momid, smoke) <span class="sc">%&gt;%</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">N =</span> <span class="fu">n_distinct</span>(momid),</span>
<span id="cb16-24"><a href="#cb16-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">momid=</span> momid, </span>
<span id="cb16-25"><a href="#cb16-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">smoke =</span> smoke</span>
<span id="cb16-26"><a href="#cb16-26" aria-hidden="true" tabindex="-1"></a>    ) <span class="sc">%&gt;%</span> </span>
<span id="cb16-27"><a href="#cb16-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(smoke <span class="sc">==</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb16-28"><a href="#cb16-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(momid) <span class="sc">%&gt;%</span></span>
<span id="cb16-29"><a href="#cb16-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb16-30"><a href="#cb16-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">distinct</span>(momid, <span class="at">.keep_all =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb16-31"><a href="#cb16-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb16-32"><a href="#cb16-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">Freq =</span> <span class="fu">n</span>(), </span>
<span id="cb16-33"><a href="#cb16-33" aria-hidden="true" tabindex="-1"></a>    <span class="at">Percent =</span> Freq<span class="sc">/</span>N[<span class="dv">1</span>]</span>
<span id="cb16-34"><a href="#cb16-34" aria-hidden="true" tabindex="-1"></a>    ) </span>
<span id="cb16-35"><a href="#cb16-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-36"><a href="#cb16-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Binding group percentages for smokers and non-smokers</span></span>
<span id="cb16-37"><a href="#cb16-37" aria-hidden="true" tabindex="-1"></a>btwn<span class="ot">&lt;-</span> <span class="fu">rbind</span>(btwn_ns, btwn_s)</span>
<span id="cb16-38"><a href="#cb16-38" aria-hidden="true" tabindex="-1"></a>btwn<span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(btwn)</span>
<span id="cb16-39"><a href="#cb16-39" aria-hidden="true" tabindex="-1"></a><span class="fu">rownames</span>(btwn)<span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Nonsmoke"</span>, <span class="st">"smoke"</span>)</span>
<span id="cb16-40"><a href="#cb16-40" aria-hidden="true" tabindex="-1"></a>btwn</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         Freq   Percent
Nonsmoke 3565 0.8961790
smoke     717 0.1802413</code></pre>
</div>
</div>
</section>
</section>
<section id="the-linear-random-intercept-model-with-covariates" class="level1">
<h1>The linear random-intercept model with covariates</h1>
<section id="model-estimation-using-r-3.4" class="level2">
<h2 class="anchored" data-anchor-id="model-estimation-using-r-3.4">Model estimation using R (3.4)</h2>
<section id="using-plm-function-3.4.1" class="level3">
<h3 class="anchored" data-anchor-id="using-plm-function-3.4.1">Using <code>plm</code> function (3.4.1)</h3>
<p>We can us different R function to fit random-intercept models by maximum likelihood (ML) method. We can also estimate the random-intercept models using restricted maximum-likelihood estimation (REML) methods.To estimate random intercept model, we can use R-PLM package, and <code>plm</code> function</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To estimate random intercept model, we can use R-PLM package, and plm function. </span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>model_formula_1<span class="ot">&lt;-</span> birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span>somecoll<span class="sc">+</span> collgrad<span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span> kessner2<span class="sc">+</span> kessner3<span class="sc">+</span> novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>model_1<span class="ot">&lt;-</span> <span class="fu">plm</span>(</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">formula=</span> model_formula_1, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df, </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">model =</span> <span class="st">"random"</span>, </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"momid"</span>),</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">vcov =</span> vcovHC</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Oneway (individual) effect Random Effect Model 
   (Swamy-Arora's transformation)

Call:
plm(formula = model_formula_1, data = df, model = "random", index = c("momid"), 
    vcov = vcovHC)

Unbalanced Panel: n = 3978, T = 2-3, N = 8604

Effects:
                   var  std.dev share
idiosyncratic 136100.4    368.9 0.543
individual    114687.9    338.7 0.457
theta:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.3898  0.3898  0.3898  0.4073  0.3898  0.4676 

Residuals:
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-2789.35  -217.93     2.02     0.39   235.73  1637.28 

Coefficients:
             Estimate Std. Error  z-value  Pr(&gt;|z|)    
(Intercept) 3116.7001    40.9655  76.0810 &lt; 2.2e-16 ***
smoke       -218.0810    18.1819 -11.9944 &lt; 2.2e-16 ***
male         120.9589     9.5598  12.6529 &lt; 2.2e-16 ***
mage           8.1162     1.3470   6.0256 1.685e-09 ***
hsgrad        56.8514    25.0927   2.2657 0.0234725 *  
somecoll      80.6700    27.3706   2.9473 0.0032053 ** 
collgrad      90.7878    28.0561   3.2359 0.0012125 ** 
married       49.9368    25.5609   1.9536 0.0507435 .  
black       -211.3796    28.3433  -7.4578 8.797e-14 ***
kessner2     -92.9091    19.9325  -4.6612 3.144e-06 ***
kessner3    -150.7734    40.8419  -3.6916 0.0002228 ***
novisit      -29.9843    65.7128  -0.4563 0.6481788    
pretri2       92.8035    23.1971   4.0006 6.317e-05 ***
pretri3      178.6026    51.6507   3.4579 0.0005444 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    1364600000
Residual Sum of Squares: 1179100000
R-Squared:      0.13613
Adj. R-Squared: 0.13482
Chisq: 691.51 on 13 DF, p-value: &lt; 2.22e-16</code></pre>
</div>
</div>
<p>The error estimates in the estimated model are not robust. To estimate the robust standard errors, we need to run additional codes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us use the following code to obtain the robust standard errors.</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>model_2<span class="ot">&lt;-</span> <span class="fu">coeftest</span>(</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>                 model_1, </span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">vcov.=</span><span class="cf">function</span>(x)<span class="fu">vcovHC</span>(x, <span class="at">type =</span><span class="st">'sss'</span>)</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>                 )</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us have a look at the estimates now. </span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>model_2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
t test of coefficients:

             Estimate Std. Error  t value  Pr(&gt;|t|)    
(Intercept) 3116.7001    42.5581  73.2340 &lt; 2.2e-16 ***
smoke       -218.0810    19.1536 -11.3859 &lt; 2.2e-16 ***
male         120.9589     9.6759  12.5011 &lt; 2.2e-16 ***
mage           8.1162     1.4069   5.7690 8.252e-09 ***
hsgrad        56.8514    25.8369   2.2004 0.0278056 *  
somecoll      80.6700    28.4048   2.8400 0.0045217 ** 
collgrad      90.7878    29.1407   3.1155 0.0018424 ** 
married       49.9368    26.6328   1.8750 0.0608248 .  
black       -211.3796    29.3201  -7.2094 6.097e-13 ***
kessner2     -92.9091    21.6607  -4.2893 1.812e-05 ***
kessner3    -150.7734    40.9919  -3.6781 0.0002364 ***
novisit      -29.9843    80.9585  -0.3704 0.7111187    
pretri2       92.8035    24.7580   3.7484 0.0001791 ***
pretri3      178.6026    52.8980   3.3764 0.0007378 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>we may also separate the estimated coefficients from the model summary.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated coefficients.</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_1)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error     z-value     Pr(&gt;|z|)
(Intercept) 3116.700072  40.965529  76.0810401 0.000000e+00
smoke       -218.081046  18.181887 -11.9944124 3.801052e-33
male         120.958855   9.559808  12.6528540 1.078834e-36
mage           8.116159   1.346955   6.0255612 1.685239e-09
hsgrad        56.851398  25.092704   2.2656545 2.347254e-02
somecoll      80.670048  27.370574   2.9473276 3.205334e-03
collgrad      90.787786  28.056143   3.2359325 1.212461e-03
married       49.936780  25.560852   1.9536430 5.074345e-02
black       -211.379557  28.343347  -7.4578191 8.796635e-14
kessner2     -92.909080  19.932487  -4.6611886 3.143884e-06
kessner3    -150.773366  40.841850  -3.6916390 2.228136e-04
novisit      -29.984320  65.712763  -0.4562937 6.481788e-01
pretri2       92.803475  23.197144   4.0006423 6.317080e-05
pretri3      178.602617  51.650668   3.4578956 5.444124e-04</code></pre>
</div>
</div>
</section>
<section id="using-lme-function-from-lme4-r-package" class="level3">
<h3 class="anchored" data-anchor-id="using-lme-function-from-lme4-r-package">Using <code>lme</code> function from <code>lme4</code> R-package</h3>
<p>We can also use lme4 R-package to estimate the model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated random intercept model using lme4 package.</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>model_formmula_3<span class="ot">&lt;-</span>birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span>somecoll<span class="sc">+</span> collgrad<span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span> kessner2<span class="sc">+</span> kessner3<span class="sc">+</span> novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>model_3<span class="ot">&lt;-</span><span class="fu">lmer</span>(</span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">formula=</span> model_formmula_3,</span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df, </span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">REML =</span> <span class="cn">FALSE</span></span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: model_formmula_3
   Data: df

     AIC      BIC   logLik deviance df.resid 
130323.5 130436.5 -65145.8 130291.5     8588 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-6.6456 -0.4876  0.0088  0.5173  3.8520 

Random effects:
 Groups   Name        Variance Std.Dev.
 momid    (Intercept) 114763   338.8   
 Residual             137393   370.7   
Number of obs: 8604, groups:  momid, 3978

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept) 3117.191     40.888 5399.395  76.237  &lt; 2e-16 ***
smoke       -218.329     18.159 7886.248 -12.023  &lt; 2e-16 ***
male         120.937      9.558 7158.103  12.653  &lt; 2e-16 ***
mage           8.101      1.345 5853.194   6.025 1.80e-09 ***
hsgrad        56.847     25.035 4073.240   2.271 0.023219 *  
somecoll      80.686     27.309 4177.223   2.955 0.003149 ** 
collgrad      90.833     27.995 4383.545   3.245 0.001185 ** 
married       49.920     25.503 4140.667   1.957 0.050365 .  
black       -211.414     28.278 3969.218  -7.476 9.35e-14 ***
kessner2     -92.919     19.926 7629.725  -4.663 3.17e-06 ***
kessner3    -150.876     40.830 7511.541  -3.695 0.000221 ***
novisit      -30.030     65.692 7644.866  -0.457 0.647583    
pretri2       92.858     23.191 7496.590   4.004 6.29e-05 ***
pretri3      178.730     51.637 7459.935   3.461 0.000541 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Correlation matrix not shown by default, as p = 14 &gt; 12.
Use print(x, correlation=TRUE)  or
    vcov(x)        if you need it</code></pre>
</div>
</div>
<p>Let us calculate the intra-class correlation. To get the intra-class correlation, we may wish to use the <code>performance</code> R-package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intra-class correlation.</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>performance<span class="sc">::</span><span class="fu">icc</span>(model_3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># Intraclass Correlation Coefficient

    Adjusted ICC: 0.455
  Unadjusted ICC: 0.414</code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="coefficients-of-determinations-or-variance-explained-3.5" class="level1">
<h1>Coefficients of determinations or variance explained (3.5)</h1>
<p>Coefficients of determination is denoted by R-squred, and can be explained as the proportional reduction in prediction error variance, comparing the model of interest that does not include any covariate.</p>
<p>Let us first fit the null model (unconditional model).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimation of null model</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>model_formmula_4 <span class="ot">&lt;-</span>birwt <span class="sc">~</span> (<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>model_4<span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">formula=</span> model_formmula_4, </span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> df, </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">REML =</span> F)</span>
<span id="cb29-7"><a href="#cb29-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_4)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: model_formmula_4
   Data: df

     AIC      BIC   logLik deviance df.resid 
130957.0 130978.2 -65475.5 130951.0     8601 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-6.2746 -0.4860  0.0036  0.5054  4.0506 

Random effects:
 Groups   Name        Variance Std.Dev.
 momid    (Intercept) 135635   368.3   
 Residual             142625   377.7   
Number of obs: 8604, groups:  momid, 3978

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept) 3467.969      7.138 3959.308   485.9   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Let us now fit a random-intercept model that includes only level-2 covariates</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimation of random-intercept model with level 2 variables.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>model_formula_5 <span class="ot">&lt;-</span>birwt<span class="sc">~</span> hsgrad <span class="sc">+</span> somecoll<span class="sc">+</span> collgrad<span class="sc">+</span> married<span class="sc">+</span> black<span class="sc">+</span>(<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>model_5<span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">formula =</span> model_formula_5, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">data=</span>df, </span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">REML=</span> F)</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_5)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: model_formula_5
   Data: df

     AIC      BIC   logLik deviance df.resid 
130676.5 130733.0 -65330.2 130660.5     8596 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-6.3530 -0.4896  0.0062  0.5179  4.0739 

Random effects:
 Groups   Name        Variance Std.Dev.
 momid    (Intercept) 121204   348.1   
 Residual             142705   377.8   
Number of obs: 8604, groups:  momid, 3978

Fixed effects:
            Estimate Std. Error      df t value Pr(&gt;|t|)    
(Intercept)  3216.48      25.83 3998.80 124.548  &lt; 2e-16 ***
hsgrad        131.44      24.91 3964.13   5.276 1.39e-07 ***
somecoll      180.69      26.50 3958.71   6.817 1.07e-11 ***
collgrad      232.89      25.59 3954.20   9.102  &lt; 2e-16 ***
married       114.77      25.46 3986.46   4.508 6.74e-06 ***
black        -201.48      28.80 3952.26  -6.995 3.10e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Correlation of Fixed Effects:
         (Intr) hsgrad somcll cllgrd marrid
hsgrad   -0.481                            
somecoll -0.404  0.720                     
collgrad -0.408  0.756  0.754              
married  -0.599 -0.273 -0.350 -0.392       
black    -0.363 -0.029 -0.016  0.014  0.332</code></pre>
</div>
</div>
</section>
<section id="hypothesis-tests-and-confidence-intervals-3.6" class="level1">
<h1>Hypothesis tests and confidence intervals (3.6)</h1>
<section id="hypothesis-tests-for-inidividual-regression-coefficients-3.6.1" class="level2">
<h2 class="anchored" data-anchor-id="hypothesis-tests-for-inidividual-regression-coefficients-3.6.1">Hypothesis tests for inidividual regression coefficients (3.6.1)</h2>
<p>The most common hypothesis test for individual regression coefficient is given below.</p>
<p>Considering the <span class="math inline">\(\beta_2\)</span> as the coefficient of interest, the hypothesis is:</p>
<p><span class="math inline">\(H_0 : \beta_2 = 0\)</span> vs <span class="math inline">\(H_a : \beta_2 = 0\)</span></p>
<p>To test the hypothesis, following test statistic is used.</p>
<p><span class="math inline">\(z = \frac{\widehat{\beta_2}}{\widehat{SE}(\widehat{\beta})}\)</span></p>
<p>Let us fit the random-effect model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Random effect model explaining birth weight.</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>model_formula_6<span class="ot">&lt;-</span>birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span>somecoll<span class="sc">+</span> collgrad<span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span> kessner2<span class="sc">+</span> kessner3<span class="sc">+</span> novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>model_6<span class="ot">&lt;-</span> lmerTest<span class="sc">::</span><span class="fu">lmer</span>(</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">formula=</span> model_formula_6,</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">data =</span> df, </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">REML=</span> <span class="cn">TRUE</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>                         )</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_6)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by REML. t-tests use Satterthwaite's method [
lmerModLmerTest]
Formula: model_formula_6
   Data: df

REML criterion at convergence: 130187

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-6.6404 -0.4873  0.0088  0.5165  3.8518 

Random effects:
 Groups   Name        Variance Std.Dev.
 momid    (Intercept) 115112   339.3   
 Residual             137535   370.9   
Number of obs: 8604, groups:  momid, 3978

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept) 3117.080     40.931 5389.733  76.154  &lt; 2e-16 ***
smoke       -218.273     18.176 7873.740 -12.009  &lt; 2e-16 ***
male         120.942      9.564 7148.154  12.645  &lt; 2e-16 ***
mage           8.104      1.346 5843.743   6.021 1.84e-09 ***
hsgrad        56.848     25.064 4065.581   2.268 0.023375 *  
somecoll      80.682     27.340 4169.383   2.951 0.003185 ** 
collgrad      90.823     28.026 4375.410   3.241 0.001202 ** 
married       49.924     25.532 4132.762   1.955 0.050611 .  
black       -211.406     28.310 3961.755  -7.467 1.00e-13 ***
kessner2     -92.917     19.940 7618.404  -4.660 3.22e-06 ***
kessner3    -150.853     40.859 7500.594  -3.692 0.000224 ***
novisit      -30.020     65.738 7633.598  -0.457 0.647928    
pretri2       92.846     23.207 7485.619   4.001 6.37e-05 ***
pretri3      178.701     51.672 7449.066   3.458 0.000547 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Correlation matrix not shown by default, as p = 14 &gt; 12.
Use print(x, correlation=TRUE)  or
    vcov(x)        if you need it</code></pre>
</div>
</div>
<p>We can also separate the estimated coefficients from the estimated model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients from estimated random effect model</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_6)<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Estimate Std. Error       df     t value     Pr(&gt;|t|)
(Intercept) 3117.079818  40.931484 5389.733  76.1535995 0.000000e+00
smoke       -218.272643  18.175975 7873.740 -12.0088544 6.185387e-33
male         120.942342   9.564434 7148.154  12.6450072 2.909075e-36
mage           8.104088   1.345959 5843.743   6.0210500 1.838304e-09
hsgrad        56.848137  25.064158 4065.581   2.2681048 2.337505e-02
somecoll      80.682457  27.340181 4169.383   2.9510579 3.184515e-03
collgrad      90.822559  28.026448 4375.410   3.2406019 1.201706e-03
married       49.923970  25.532224 4132.762   1.9553318 5.061122e-02
black       -211.406032  28.310311 3961.755  -7.4674570 9.999426e-14
kessner2     -92.916616  19.940157 7618.404  -4.6597734 3.219340e-06
kessner3    -150.852581  40.858623 7500.594  -3.6920623 2.240219e-04
novisit      -30.019915  65.737826 7633.598  -0.4566612 6.479276e-01
pretri2       92.845522  23.206746 7485.619   4.0007989 6.373734e-05
pretri3      178.700674  51.672452 7449.066   3.4583355 5.465644e-04</code></pre>
</div>
</div>
</section>
<section id="joint-hypothesis-test-for-several-regression-coefficient-3.6.2." class="level2">
<h2 class="anchored" data-anchor-id="joint-hypothesis-test-for-several-regression-coefficient-3.6.2.">Joint hypothesis test for several regression coefficient (3.6.2).</h2>
<p>Let us consider a null hypothesis that the regression coefficients of two covariates <span class="math inline">\(x_{2ij}\)</span> and <span class="math inline">\(x_{3ij}\)</span> are both 0.</p>
<p>So the hypothesis is:</p>
<p><span class="math inline">\(H_0 : \beta_2 = \beta_3 = 0\)</span></p>
<p>vs</p>
<p><span class="math inline">\(H_a\)</span> : At least one of the parameter is nonzero.</p>
<p>We can perform Wald test to check the above hypothesis. We can also check all <span class="math inline">\(\beta\)</span> coefficients at a time. The following R-code shows Chi-square tests to check for the significance of each variable used in the random effect model.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us specify the random effect model first.</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="co"># We need to use glmer() function in lme4 package to perform chi-square test. </span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>model_formula_7<span class="ot">&lt;-</span>birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span>somecoll<span class="sc">+</span> collgrad<span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span> kessner2<span class="sc">+</span> kessner3<span class="sc">+</span> novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>model_7<span class="ot">&lt;-</span> <span class="fu">glmer</span>(</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">formula=</span> model_formula_7,</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a>                 <span class="at">data =</span> df </span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>                 )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in glmer(formula = model_formula_7, data = df): calling glmer() with
family=gaussian (identity link) as a shortcut to lmer() is deprecated; please
call lmer() directly</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test of significance of coefficients. </span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">drop1</span>(model_7, <span class="at">test =</span> <span class="st">"Chisq"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Single term deletions

Model:
birwt ~ smoke + male + mage + hsgrad + somecoll + collgrad + 
    married + black + kessner2 + kessner3 + novisit + pretri2 + 
    pretri3 + (1 | momid)
         npar    AIC     LRT   Pr(Chi)    
&lt;none&gt;        130324                      
smoke       1 130463 141.899 &lt; 2.2e-16 ***
male        1 130480 158.150 &lt; 2.2e-16 ***
mage        1 130358  36.183 1.796e-09 ***
hsgrad      1 130327   5.153 0.0232081 *  
somecoll    1 130330   8.719 0.0031492 ** 
collgrad    1 130332  10.510 0.0011875 ** 
married     1 130325   3.830 0.0503400 .  
black       1 130377  55.459 9.542e-14 ***
kessner2    1 130343  21.715 3.162e-06 ***
kessner3    1 130335  13.644 0.0002210 ***
novisit     1 130322   0.209 0.6475730    
pretri2     1 130338  16.018 6.275e-05 ***
pretri3     1 130333  11.972 0.0005401 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Based on the LRT values and Pr(Chi) values of kessner2 and kessner3, we may reject the null hypothesis, and may conclude that both kessner 2 and kessner3 have significant affect on birth weight.</p>
<p>If the number of cluster is small, with j-q &lt; 42, it is better to perform an approximate F test, which can be obtained by estimating the model by using <code>lmer()</code> function with <code>RMEL = T</code> option. In addition to providing a finite-sample approximation to the sampling distribution, this approach also has the advantage that the standard errors perform better than ML-based or robust standard errors when the number of cluster is small.</p>
<p>In R, we can perform F test for all <span class="math inline">\(\beta\)</span> -coefficients at a time. In this case, we use a R-package called “predictmeans”.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us specify the the random effect model using lme4::lmer() function.</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="co"># We are using RMEL method for the model estimation.</span></span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>model_formula_8 <span class="ot">&lt;-</span>birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span>somecoll<span class="sc">+</span> collgrad<span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span> kessner2<span class="sc">+</span> kessner3<span class="sc">+</span> novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>model_8<span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">formula =</span> model_formula_8,</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> df, </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">REML =</span> T</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>               )</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Testing all parameters of random effect model using F-test.</span></span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-12"><a href="#cb42-12" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_8)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Type III Analysis of Variance Table with Satterthwaite's method
           Sum Sq  Mean Sq NumDF  DenDF  F value    Pr(&gt;F)    
smoke    19834323 19834323     1 7873.7 144.2126 &lt; 2.2e-16 ***
male     21991374 21991374     1 7148.2 159.8962 &lt; 2.2e-16 ***
mage      4986074  4986074     1 5843.7  36.2530 1.838e-09 ***
hsgrad     707523   707523     1 4065.6   5.1443 0.0233751 *  
somecoll  1197760  1197760     1 4169.4   8.7087 0.0031845 ** 
collgrad  1444327  1444327     1 4375.4  10.5015 0.0012017 ** 
married    525842   525842     1 4132.8   3.8233 0.0506112 .  
black     7669370  7669370     1 3961.8  55.7629 9.999e-14 ***
kessner2  2986371  2986371     1 7618.4  21.7135 3.219e-06 ***
kessner3  1874788  1874788     1 7500.6  13.6313 0.0002240 ***
novisit     28682    28682     1 7633.6   0.2085 0.6479276    
pretri2   2201444  2201444     1 7485.6  16.0064 6.374e-05 ***
pretri3   1644934  1644934     1 7449.1  11.9601 0.0005466 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
<p>Moreover, if we wish to test the significance of Kessner2 and Kessner3 only, in that case we can specify two models i.e., first model with all variables, and the second model with all variables excluding Kessner2 and Kessner3. Then we can compare the models to check significance of these variables.</p>
<p>For instance, we are trying to test the following hypothesis.</p>
<p><span class="math inline">\(H_0 : \beta_2 = \beta_3 = 0\)</span></p>
<p>vs</p>
<p><span class="math inline">\(H_a\)</span> : At least one of the parameter is nonzero.</p>
<p>We can perform a likelihood-ratio test, and the test statistic is</p>
<p><span class="math inline">\(L= 2(l_1-l_0)\)</span></p>
<p>Where <span class="math inline">\(l_1\)</span> and <span class="math inline">\(l_0\)</span> are now the maximized log likelihoods for the models including and excluding both kessner2 and kessner3, respectively.</p>
<p>Under the null hypothesis, the likelihood-ratio statistic also has an asymptotic <span class="math inline">\(\chi^2\)</span> distribution.</p>
<p>A likelihod-ratio test of the null hypothesis that the coefficients of the dummy variables kessner2 and kessner3 are both 0 can be performed by estimating both models by maximum likelihood and then using <code>anova()</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us specify random effect model with kessner2 and kessner3</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>formula_model_9 <span class="ot">&lt;-</span> birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span>somecoll<span class="sc">+</span> collgrad<span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span> kessner2<span class="sc">+</span> kessner3<span class="sc">+</span> novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>model_9<span class="ot">&lt;-</span><span class="fu">lmer</span>(</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula =</span> formula_model_9,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> df, </span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">REML =</span> F</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>              )</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Let us specify random effect model without kessner2 and kessner3</span></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a>formula_model_10<span class="ot">&lt;-</span>birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span>somecoll<span class="sc">+</span> collgrad <span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span>novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>model_10<span class="ot">&lt;-</span><span class="fu">lmer</span>(</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>           <span class="at">formula =</span> formula_model_10,</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df, </span>
<span id="cb44-15"><a href="#cb44-15" aria-hidden="true" tabindex="-1"></a>           <span class="at">REML =</span> F</span>
<span id="cb44-16"><a href="#cb44-16" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb44-17"><a href="#cb44-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-18"><a href="#cb44-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us perform the likelihood ratio test</span></span>
<span id="cb44-19"><a href="#cb44-19" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_9, model_10)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Data: df
Models:
model_10: formula_model_10
model_9: formula_model_9
         npar    AIC    BIC logLik deviance  Chisq Df Pr(&gt;Chisq)    
model_10   14 130346 130445 -65159   130318                         
model_9    16 130324 130436 -65146   130292 26.896  2  1.444e-06 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>
</section>
</section>
<section id="between-and-within-effects-of-level-1-covariates-3.7" class="level1">
<h1>Between and within effects of level-1 covariates (3.7)</h1>
<p>We now turn to the estimated regression coefficients for the random intercept model with covariates. We will proceed to analyse between mother comparisons, and within-mother comparisons.</p>
<section id="between-mother-effects3.7.1" class="level2">
<h2 class="anchored" data-anchor-id="between-mother-effects3.7.1">Between-mother effects(3.7.1)</h2>
<p>To estimate between-mother effects we can use `plm()’ function of plm R-package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us specify the model using plm() function for estimating between mother effects.</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>formula_model_11<span class="ot">&lt;-</span> birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span> somecoll <span class="sc">+</span> collgrad<span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span> kessner2<span class="sc">+</span> kessner3<span class="sc">+</span> novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>model_11<span class="ot">&lt;-</span> <span class="fu">plm</span>(</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>               <span class="at">formula =</span> formula_model_11, </span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>               <span class="at">data =</span> df, </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>               <span class="at">model =</span> <span class="st">"between"</span>, </span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>               <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"momid"</span>)</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>               )</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_11)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Oneway (individual) effect Between Model

Call:
plm(formula = formula_model_11, data = df, model = "between", 
    index = c("momid"))

Unbalanced Panel: n = 3978, T = 2-3, N = 8604
Observations used in estimation: 3978

Residuals:
      Min.    1st Qu.     Median    3rd Qu.       Max. 
-1805.2899  -258.4683     8.1519   266.4240  1599.9828 

Coefficients:
             Estimate Std. Error  t-value  Pr(&gt;|t|)    
(Intercept) 3241.4496    46.1596  70.2227 &lt; 2.2e-16 ***
smoke       -286.1476    23.2255 -12.3204 &lt; 2.2e-16 ***
male         104.9432    19.4953   5.3830  7.75e-08 ***
mage           4.3987     1.5054   2.9219 0.0034992 ** 
hsgrad        58.8098    25.5142   2.3050 0.0212192 *  
somecoll      85.0713    28.1348   3.0237 0.0025130 ** 
collgrad      99.8751    29.3532   3.4025 0.0006743 ***
married       41.9127    26.1072   1.6054 0.1084838    
black       -218.4045    28.5784  -7.6423  2.66e-14 ***
kessner2    -101.4931    37.6561  -2.6953 0.0070629 ** 
kessner3    -201.9599    79.2882  -2.5472 0.0108978 *  
novisit      -51.0273   124.2073  -0.4108 0.6812238    
pretri2      125.4776    44.7201   2.8058 0.0050429 ** 
pretri3      241.1201   100.6567   2.3955 0.0166452 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    809620000
Residual Sum of Squares: 715090000
R-Squared:      0.11676
Adj. R-Squared: 0.11386
F-statistic: 40.3099 on 13 and 3964 DF, p-value: &lt; 2.22e-16</code></pre>
</div>
</div>
</section>
<section id="within-mother-effects3.7.2" class="level2">
<h2 class="anchored" data-anchor-id="within-mother-effects3.7.2">Within-mother effects(3.7.2)</h2>
<p>To estimate between-mother effects we can use `plm()’ function of plm R-package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us specify the model using plm() function for estimating between mother effects.</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>formula_model_12<span class="ot">&lt;-</span>birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span> somecoll <span class="sc">+</span> collgrad<span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span> kessner2<span class="sc">+</span> kessner3<span class="sc">+</span> novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>model_12<span class="ot">&lt;-</span> <span class="fu">plm</span>(</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">formula=</span> formula_model_12, </span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df, </span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">model =</span> <span class="st">"within"</span>, </span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a>           <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"momid"</span>)</span>
<span id="cb48-9"><a href="#cb48-9" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb48-10"><a href="#cb48-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-11"><a href="#cb48-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_12)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Oneway (individual) effect Within Model

Call:
plm(formula = formula_model_12, data = df, model = "within", 
    index = c("momid"))

Unbalanced Panel: n = 3978, T = 2-3, N = 8604

Residuals:
       Min.     1st Qu.      Median     3rd Qu.        Max. 
-1953.07916  -156.47605     0.33512   158.92707  1953.07916 

Coefficients:
          Estimate Std. Error t-value  Pr(&gt;|t|)    
smoke    -104.5494    29.1008 -3.5927 0.0003307 ***
male      125.6355    10.9227 11.5022 &lt; 2.2e-16 ***
mage       23.1583     3.0067  7.7023 1.624e-14 ***
kessner2  -91.4948    23.4891 -3.8952 9.951e-05 ***
kessner3 -128.0910    47.7964 -2.6799 0.0073898 ** 
novisit    -4.8059    77.7721 -0.0618 0.9507291    
pretri2    81.2904    27.0497  3.0052 0.0026682 ** 
pretri3   153.0590    60.0845  2.5474 0.0108852 *  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    659130000
Residual Sum of Squares: 628510000
R-Squared:      0.046453
Adj. R-Squared: -0.77639
F-statistic: 28.1215 on 8 and 4618 DF, p-value: &lt; 2.22e-16</code></pre>
</div>
</div>
</section>
<section id="random-intercept-model" class="level2">
<h2 class="anchored" data-anchor-id="random-intercept-model">Random intercept model</h2>
<p>For comparison purpose, let us also estimate the random intercept model using `plm()’ function of plm R-package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us specify the model using plm() function for estimating between mother effects.</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>formula_model_13 <span class="ot">&lt;-</span> birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span> somecoll <span class="sc">+</span> collgrad<span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span> kessner2<span class="sc">+</span> kessner3<span class="sc">+</span> novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>model_13<span class="ot">&lt;-</span> <span class="fu">plm</span>(</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">formula =</span> formula_model_13, </span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> df, </span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">model =</span> <span class="st">"random"</span>, </span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">index =</span> <span class="fu">c</span>(<span class="st">"momid"</span>)</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>           )</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_13)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Oneway (individual) effect Random Effect Model 
   (Swamy-Arora's transformation)

Call:
plm(formula = formula_model_13, data = df, model = "random", 
    index = c("momid"))

Unbalanced Panel: n = 3978, T = 2-3, N = 8604

Effects:
                   var  std.dev share
idiosyncratic 136100.4    368.9 0.543
individual    114687.9    338.7 0.457
theta:
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.3898  0.3898  0.3898  0.4073  0.3898  0.4676 

Residuals:
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-2789.35  -217.93     2.02     0.39   235.73  1637.28 

Coefficients:
             Estimate Std. Error  z-value  Pr(&gt;|z|)    
(Intercept) 3116.7001    40.9655  76.0810 &lt; 2.2e-16 ***
smoke       -218.0810    18.1819 -11.9944 &lt; 2.2e-16 ***
male         120.9589     9.5598  12.6529 &lt; 2.2e-16 ***
mage           8.1162     1.3470   6.0256 1.685e-09 ***
hsgrad        56.8514    25.0927   2.2657 0.0234725 *  
somecoll      80.6700    27.3706   2.9473 0.0032053 ** 
collgrad      90.7878    28.0561   3.2359 0.0012125 ** 
married       49.9368    25.5609   1.9536 0.0507435 .  
black       -211.3796    28.3433  -7.4578 8.797e-14 ***
kessner2     -92.9091    19.9325  -4.6612 3.144e-06 ***
kessner3    -150.7734    40.8419  -3.6916 0.0002228 ***
novisit      -29.9843    65.7128  -0.4563 0.6481788    
pretri2       92.8035    23.1971   4.0006 6.317e-05 ***
pretri3      178.6026    51.6507   3.4579 0.0005444 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Total Sum of Squares:    1364600000
Residual Sum of Squares: 1179100000
R-Squared:      0.13613
Adj. R-Squared: 0.13482
Chisq: 691.51 on 13 DF, p-value: &lt; 2.22e-16</code></pre>
</div>
</div>
</section>
<section id="conventional-hausman-test3.7.5" class="level2">
<h2 class="anchored" data-anchor-id="conventional-hausman-test3.7.5">Conventional Hausman Test(3.7.5)</h2>
<p>The Hauseman test can be used to compare two alternative estimators of <span class="math inline">\(\beta\)</span>, both of which are consistent if the model is correct. In its standard form, one of the estimator is asymptotically efficient if the model is correct, but is inconsistent when the model is misspecified.</p>
<p>Hausemen test can be easily performed using <code>phtest()</code> function in plm R-package.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Let us use mod11 and mod12 to perform the Hauseman test.</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>plm<span class="sc">::</span><span class="fu">phtest</span>(model_11, model_12)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Hausman Test

data:  formula_model_11
chisq = 59.995, df = 8, p-value = 4.671e-10
alternative hypothesis: one model is inconsistent</code></pre>
</div>
</div>
<p>There is a strong evidence for model misspecification as Hausment test returned with a p-value &lt;0.001.</p>
</section>
<section id="allowing-for-different-within-and-between-effects3.7.6" class="level2">
<h2 class="anchored" data-anchor-id="allowing-for-different-within-and-between-effects3.7.6">Allowing for different within and between effects(3.7.6)</h2>
<p>We will now estimate random intercept model with the cluster mean of smoke (i.e., the proportion of pregnancies in which the mother smokes), as well as the child-specific deviation from the cluster mean of smoke as covariates. Before we proceed with the modeling part, we need to restructure the data and calculate the clustered means for different mothers.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We are creating mn_smoke and dev_smok variables in df1 dataset.</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>df1<span class="ot">&lt;-</span>df <span class="sc">%&gt;%</span> </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(momid) <span class="sc">%&gt;%</span> </span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mn_smoke =</span> <span class="fu">mean</span>(smoke, <span class="at">na.rm =</span>T)) <span class="sc">%&gt;%</span> </span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">dev_smoke =</span> (smoke <span class="sc">-</span> mn_smoke))</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimation of random-effect model using `lmer()` function</span></span>
<span id="cb54-8"><a href="#cb54-8" aria-hidden="true" tabindex="-1"></a>model_formula_14<span class="ot">&lt;-</span> birwt <span class="sc">~</span> dev_smoke <span class="sc">+</span> mn_smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span> somecoll <span class="sc">+</span> collgrad  <span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span>kessner2<span class="sc">+</span> kessner3<span class="sc">+</span>novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb54-9"><a href="#cb54-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-10"><a href="#cb54-10" aria-hidden="true" tabindex="-1"></a>model_14<span class="ot">&lt;-</span><span class="fu">lmer</span>(</span>
<span id="cb54-11"><a href="#cb54-11" aria-hidden="true" tabindex="-1"></a>              <span class="at">formula=</span>model_formula_14 , </span>
<span id="cb54-12"><a href="#cb54-12" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> df1, </span>
<span id="cb54-13"><a href="#cb54-13" aria-hidden="true" tabindex="-1"></a>              <span class="at">REML =</span> F</span>
<span id="cb54-14"><a href="#cb54-14" aria-hidden="true" tabindex="-1"></a>              )</span>
<span id="cb54-15"><a href="#cb54-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-16"><a href="#cb54-16" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_14)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: model_formula_14
   Data: df1

     AIC      BIC   logLik deviance df.resid 
130300.7 130420.7 -65133.3 130266.7     8587 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-6.6679 -0.4855  0.0125  0.5144  3.9497 

Random effects:
 Groups   Name        Variance Std.Dev.
 momid    (Intercept) 114553   338.5   
 Residual             136936   370.0   
Number of obs: 8604, groups:  momid, 3978

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept) 3154.800     41.530 5134.780  75.965  &lt; 2e-16 ***
dev_smoke   -104.233     29.182 4606.866  -3.572 0.000358 ***
mn_smoke    -289.904     23.129 3993.966 -12.534  &lt; 2e-16 ***
male         121.150      9.543 7162.447  12.695  &lt; 2e-16 ***
mage           8.192      1.343 5863.673   6.100 1.13e-09 ***
hsgrad        43.101     25.157 4021.511   1.713 0.086740 .  
somecoll      62.745     27.512 4095.906   2.281 0.022621 *  
collgrad      66.898     28.369 4226.927   2.358 0.018414 *  
married       35.212     25.643 4082.749   1.373 0.169772    
black       -218.969     28.285 3966.354  -7.742 1.24e-14 ***
kessner2     -92.033     19.897 7632.377  -4.626 3.80e-06 ***
kessner3    -149.277     40.769 7514.736  -3.662 0.000252 ***
novisit      -23.392     65.605 7647.521  -0.357 0.721428    
pretri2       92.340     23.155 7499.636   3.988 6.73e-05 ***
pretri3      176.774     51.559 7463.150   3.429 0.000610 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Correlation matrix not shown by default, as p = 15 &gt; 12.
Use print(x, correlation=TRUE)  or
    vcov(x)        if you need it</code></pre>
</div>
</div>
<p>To estimate the clustering effects of other variables in the dataset, let us calculate means of other variables by momid.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We already have mn_smoke. So let us calculate mean of other variable groupe by momid. </span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>df2 <span class="ot">&lt;-</span> df1 <span class="sc">%&gt;%</span> </span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(momid) <span class="sc">%&gt;%</span> </span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">mn_male =</span> <span class="fu">mean</span>(male, <span class="at">na.rm =</span>T), </span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">mn_mage =</span> <span class="fu">mean</span>(mage, <span class="at">na.rm =</span>T),</span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">mn_kessner2 =</span> <span class="fu">mean</span>(kessner2, <span class="at">na.rm =</span>T),</span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">mn_kessner3 =</span> <span class="fu">mean</span>(kessner3, <span class="at">na.rm =</span>T),</span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">mn_novisit =</span> <span class="fu">mean</span>(novisit, <span class="at">na.rm =</span>T),</span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a>         <span class="at">mn_pretri2 =</span> <span class="fu">mean</span>(pretri2, <span class="at">na.rm =</span>T), </span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a>         <span class="at">mn_pretri3 =</span> <span class="fu">mean</span>(pretri3, <span class="at">na.rm =</span> T)</span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a>         ) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, let us estimate the random-effect model using cluster means of all level-1 covariates and the level-1 covariates.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># estimation of the random-effect model using cluster means of all level-1 covariates and the level-1 covariates</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>model_formula_15 <span class="ot">&lt;-</span>birwt <span class="sc">~</span> smoke <span class="sc">+</span> male<span class="sc">+</span> mage <span class="sc">+</span> hsgrad <span class="sc">+</span> somecoll <span class="sc">+</span> collgrad  <span class="sc">+</span> married <span class="sc">+</span>black<span class="sc">+</span>kessner2<span class="sc">+</span> kessner3<span class="sc">+</span>novisit <span class="sc">+</span>pretri2 <span class="sc">+</span>pretri3 <span class="sc">+</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>              <span class="sc">+</span> mn_smoke <span class="sc">+</span> mn_male <span class="sc">+</span> mn_mage <span class="sc">+</span> mn_kessner2 <span class="sc">+</span> mn_kessner3 <span class="sc">+</span> mn_novisit <span class="sc">+</span> mn_pretri2 <span class="sc">+</span> mn_pretri3 <span class="sc">+</span> (<span class="dv">1</span><span class="sc">|</span>momid)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>model_15<span class="ot">&lt;-</span><span class="fu">lmer</span>(</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>            <span class="at">formula =</span> model_formula_15, </span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">data =</span> df2, </span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>            <span class="at">REML =</span> F</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>            )</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_15)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Linear mixed model fit by maximum likelihood . t-tests use Satterthwaite's
  method [lmerModLmerTest]
Formula: model_formula_15
   Data: df2

     AIC      BIC   logLik deviance df.resid 
130279.7 130449.1 -65115.8 130231.7     8580 

Scaled residuals: 
    Min      1Q  Median      3Q     Max 
-6.6725 -0.4866  0.0098  0.5132  3.9136 

Random effects:
 Groups   Name        Variance Std.Dev.
 momid    (Intercept) 114543   338.4   
 Residual             136152   369.0   
Number of obs: 8604, groups:  momid, 3978

Fixed effects:
            Estimate Std. Error       df t value Pr(&gt;|t|)    
(Intercept) 3238.407     45.989 3974.022  70.417  &lt; 2e-16 ***
smoke       -104.549     29.106 4614.992  -3.592 0.000332 ***
male         125.635     10.925 4614.992  11.500  &lt; 2e-16 ***
mage          23.158      3.007 4614.992   7.701 1.64e-14 ***
hsgrad        56.297     25.386 3950.987   2.218 0.026638 *  
somecoll      83.070     27.991 3949.166   2.968 0.003018 ** 
collgrad      98.176     29.187 3939.764   3.364 0.000776 ***
married       42.461     26.032 3988.053   1.631 0.102938    
black       -219.001     28.418 3940.482  -7.707 1.63e-14 ***
kessner2     -91.495     23.494 4614.992  -3.894 9.98e-05 ***
kessner3    -128.091     47.805 4614.992  -2.679 0.007401 ** 
novisit       -4.806     77.787 4614.992  -0.062 0.950738    
pretri2       81.290     27.055 4614.992   3.005 0.002673 ** 
pretri3      153.059     60.096 4614.992   2.547 0.010900 *  
mn_smoke    -183.166     37.197 8408.857  -4.924 8.63e-07 ***
mn_male      -20.224     22.310 6367.703  -0.906 0.364720    
mn_mage      -18.594      3.360 6720.519  -5.534 3.26e-08 ***
mn_kessner2   -9.051     44.222 6791.081  -0.205 0.837838    
mn_kessner3  -79.425     92.269 6643.929  -0.861 0.389384    
mn_novisit   -38.116    146.322 6845.240  -0.260 0.794489    
mn_pretri2    44.767     52.060 6648.663   0.860 0.389871    
mn_pretri3    96.070    116.707 6581.397   0.823 0.410436    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>
Correlation matrix not shown by default, as p = 22 &gt; 12.
Use print(x, correlation=TRUE)  or
    vcov(x)        if you need it</code></pre>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>